# Generated by Django 5.1.3 on 2025-05-18 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('level', models.IntegerField(default=1)),
                ('experience', models.IntegerField(default=0)),
                ('experience_needed', models.IntegerField(default=100)),
                ('streak', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('gems', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('theme_preference', models.CharField(choices=[('dark_blue', 'Dark Blue'), ('shadow_purple', 'Shadow Purple'), ('blood_red', 'Blood Red'), ('neon_green', 'Neon Green')], default='dark_blue', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('medal_type', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('legendary', 'Legendary')], max_length=20)),
                ('acquired_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='users.profile')),
            ],
        ),
    ]
