# Generated by Django 5.1.3 on 2025-05-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_is_equipped_shopitem_boost_duration_and_more'),
        ('users', '0002_characterclass_profile_character_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_effects',
            field=models.ManyToManyField(blank=True, related_name='users_with_effect', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_frame',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='title_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
