# Generated by Django 5.1.3 on 2025-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_active_effects_profile_avatar_frame_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active_effects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar_frame',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='background',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title_color',
        ),
    ]
