services:
  web:
    image: sim
    build: 
      context: .
    ports:          
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: sim.settings
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/simulator
      SPRING_DATASOURCE_USERNAME: 'postgres'
      SPRING_DATASOURCE_PASSWORD: 1908

  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: 1908
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'simulator'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simulator"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
