# Generated by Django 5.1.3 on 2025-06-06 13:51

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duels', '0001_initial'),
        ('tasks', '0005_remove_task_base_task_basetaskcompletion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
        migrations.AlterField(
            model_name='duel',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duel',
            name='coins_stake',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duels_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duel',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('active', 'В процессе'), ('completed', 'Завершена'), ('declined', 'Отклонена')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='duel',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task'),
        ),
    ]
