# Generated by Django 5.2.4 on 2026-01-01 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('duels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('experience_reward', models.IntegerField(default=0)),
                ('coins_reward', models.IntegerField(default=0)),
                ('gems_reward', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('task_complete', 'Завершение задачи'), ('tournament_join', 'Участие в турнире'), ('tournament_win', 'Победа в турнире'), ('duel_complete', 'Завершение дуэли'), ('chest_open', 'Открытие сундука'), ('level_up', 'Повышение уровня'), ('achievement', 'Получение достижения')], max_length=20)),
                ('description', models.TextField()),
                ('experience_gained', models.IntegerField(default=0)),
                ('coins_gained', models.IntegerField(default=0)),
                ('gems_gained', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='duels.duel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
