# Generated by Django 5.1.3 on 2025-05-18 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], max_length=20)),
                ('price_coins', models.IntegerField()),
                ('price_gems', models.IntegerField()),
                ('min_coins_reward', models.IntegerField()),
                ('max_coins_reward', models.IntegerField()),
                ('min_gems_reward', models.IntegerField()),
                ('max_gems_reward', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('coins', 'Монеты'), ('gems', 'Кристаллы')], max_length=10)),
                ('category', models.CharField(choices=[('avatar_frame', 'Рамка аватара'), ('title', 'Титул'), ('background', 'Фон профиля'), ('effect', 'Визуальный эффект'), ('boost', 'Ускоритель'), ('chest', 'Сундук')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChestOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_reward', models.IntegerField()),
                ('gems_reward', models.IntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.chest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chest_openings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem')),
            ],
        ),
    ]
