# Generated by Django 5.2.4 on 2026-01-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], max_length=20)),
                ('price_coins', models.IntegerField()),
                ('price_gems', models.IntegerField()),
                ('min_coins_reward', models.IntegerField()),
                ('max_coins_reward', models.IntegerField()),
                ('min_gems_reward', models.IntegerField()),
                ('max_gems_reward', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chest_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ChestOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_reward', models.IntegerField()),
                ('gems_reward', models.IntegerField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('is_equipped', models.BooleanField(default=False, help_text='Whether this item is currently equipped')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('coins', 'Монеты'), ('gems', 'Кристаллы')], max_length=10)),
                ('category', models.CharField(choices=[('avatar_frame', 'Рамка аватара'), ('title', 'Титул'), ('background', 'Фон профиля'), ('effect', 'Визуальный эффект'), ('boost', 'Ускоритель'), ('chest', 'Сундук')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_text', models.CharField(blank=True, help_text='For title items', max_length=100, null=True)),
                ('title_color', models.CharField(blank=True, help_text='Hex color for title', max_length=7, null=True)),
                ('frame_style', models.CharField(blank=True, help_text='For avatar frames', max_length=100, null=True)),
                ('background_url', models.CharField(blank=True, help_text='For background items', max_length=255, null=True)),
                ('effect_class', models.CharField(blank=True, help_text='CSS class for visual effect', max_length=100, null=True)),
                ('boost_multiplier', models.FloatField(default=1.0, help_text='For boost items')),
                ('boost_duration', models.IntegerField(default=0, help_text='Duration in hours for boosts')),
            ],
        ),
    ]
