# Generated by Django 5.2.4 on 2026-01-01 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activeboost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_boosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chestopening',
            name='chest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.chest'),
        ),
        migrations.AddField(
            model_name='chestopening',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chest_openings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='activeboost',
            name='boost_item',
            field=models.ForeignKey(limit_choices_to={'category': 'boost'}, on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem'),
        ),
    ]
