# Generated by Django 5.1.3 on 2025-05-21 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_equipped',
            field=models.BooleanField(default=False, help_text='Whether this item is currently equipped'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='boost_duration',
            field=models.IntegerField(default=0, help_text='Duration in hours for boosts'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='boost_multiplier',
            field=models.FloatField(default=1.0, help_text='For boost items'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='frame_style',
            field=models.CharField(blank=True, help_text='For avatar frames', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='title_color',
            field=models.CharField(blank=True, help_text='Hex color for title', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='title_text',
            field=models.CharField(blank=True, help_text='For title items', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ActiveBoost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('boost_item', models.ForeignKey(limit_choices_to={'category': 'boost'}, on_delete=django.db.models.deletion.CASCADE, to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_boosts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
