# Generated by Django 5.1.3 on 2025-05-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_purchase_is_equipped_shopitem_boost_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chest_images/'),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='background_url',
            field=models.CharField(blank=True, help_text='For background items', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='effect_class',
            field=models.CharField(blank=True, help_text='CSS class for visual effect', max_length=100, null=True),
        ),
    ]
