# Generated by Django 5.2.4 on 2026-01-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная'), ('epic', 'Эпическая')], default='medium', max_length=10)),
                ('task_type', models.CharField(choices=[('one_time', 'Одноразовая задача'), ('habit', 'Привычка'), ('daily', 'Цель на день')], default='one_time', max_length=15)),
                ('estimated_minutes', models.IntegerField(default=30, help_text='Estimated time to complete in minutes')),
                ('xp_reward', models.IntegerField(default=20, help_text='Base XP reward for completing this task')),
            ],
            options={
                'verbose_name': 'Базовая задача',
                'verbose_name_plural': 'Базовые задачи',
            },
        ),
        migrations.CreateModel(
            name='BaseTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выпелнение базовой задачи',
                'verbose_name_plural': 'Выполнение базовых задач',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная'), ('epic', 'Эпическая')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('waiting', 'Ожидает'), ('completed', 'Завершена')], default='not_started', max_length=15)),
                ('task_type', models.CharField(choices=[('one_time', 'Одноразовая задача'), ('habit', 'Привычка'), ('daily', 'Цель на день')], default='one_time', max_length=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.IntegerField(default=30, help_text='Estimated time to complete in minutes')),
                ('actual_minutes', models.IntegerField(blank=True, help_text='Actual time taken to complete in minutes', null=True)),
                ('frequency', models.CharField(default='daily', help_text='How often this habit should be performed', max_length=20)),
                ('streak', models.IntegerField(default=0, help_text='Current streak for this habit')),
                ('last_completed', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, help_text='The date this task is targeted for', null=True)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#6633ff', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Категория задачи',
                'verbose_name_plural': 'Категория задач',
            },
        ),
    ]
