# Generated by Django 5.1.3 on 2025-05-17 15:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'Task Categories'},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='taskcategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_minutes',
            field=models.IntegerField(blank=True, help_text='Actual time taken to complete in minutes', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_minutes',
            field=models.IntegerField(default=30, help_text='Estimated time to complete in minutes'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskcategory'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная'), ('epic', 'Эпическая')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начата'), ('in_progress', 'В процессе'), ('waiting', 'Ожидает'), ('completed', 'Завершена')], default='not_started', max_length=15),
        ),
        migrations.AlterField(
            model_name='taskcategory',
            name='color',
            field=models.CharField(default='#6633ff', max_length=7),
        ),
    ]
