# Generated by Django 5.1.3 on 2025-05-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskcategory_options_and_more'),
        ('users', '0002_characterclass_profile_character_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='character_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.characterclass'),
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.CharField(default='daily', help_text='How often this habit should be performed', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='streak',
            field=models.IntegerField(default=0, help_text='Current streak for this habit'),
        ),
        migrations.AddField(
            model_name='task',
            name='target_date',
            field=models.DateField(blank=True, help_text='The date this task is targeted for', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('one_time', 'Одноразовая задача'), ('habit', 'Привычка'), ('daily', 'Цель на день')], default='one_time', max_length=15),
        ),
        migrations.CreateModel(
            name='BaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная'), ('epic', 'Эпическая')], default='medium', max_length=10)),
                ('task_type', models.CharField(choices=[('one_time', 'Одноразовая задача'), ('habit', 'Привычка'), ('daily', 'Цель на день')], default='one_time', max_length=15)),
                ('estimated_minutes', models.IntegerField(default=30, help_text='Estimated time to complete in minutes')),
                ('xp_reward', models.IntegerField(default=20, help_text='Base XP reward for completing this task')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_tasks', to='users.characterclass')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='base_task',
            field=models.ForeignKey(blank=True, help_text='If this task was created from a base task', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.basetask'),
        ),
    ]
