# Generated by Django 5.1.3 on 2026-01-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basetaskcompletion',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Выполнение базовой задачи', 'verbose_name_plural': 'Выполнение базовых задач'},
        ),
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name': 'Категория задачи', 'verbose_name_plural': 'Категории задач'},
        ),
        migrations.AlterUniqueTogether(
            name='basetaskcompletion',
            unique_together=set(),
        ),
    ]
