# Generated by Django 5.2.4 on 2026-01-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_basetaskcompletion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.CharField(blank=True, default='daily', help_text='How often this habit should be performed', max_length=20),
        ),
    ]
