# Generated by Django 5.1.3 on 2025-05-21 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskcompletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='base_task',
        ),
        migrations.CreateModel(
            name='BaseTaskCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('base_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.basetask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_base_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'base_task', 'completed_at')},
            },
        ),
        migrations.DeleteModel(
            name='TaskCompletion',
        ),
    ]
