name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Copy files to server
      run: |
        ssh -o StrictHostKeyChecking=no root@195.133.194.45 "cd ~/myproject && git pull origin main && docker compose down && docker compose up -d --build"
